---
title: "Untitled"
author: "HyunJoon Bok"
date: "December 2, 2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill 
    source_code: https://github.com/hyunjoonbok
    social: ["linkedin"]
runtime: shiny_prerendered
---

```{r setup global, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(h2o)
require(keras)
library(tidyquant)
require(skimr)
library(shiny)
library(leaflet)
require(rsample)
require(iml)
require(DALEX)
require(DataExplorer)
require(tictoc)
require(lubridate)
require(plotly)
require(purrr)
require(maptools)
require(jsonlite)
require(DT)

## Data Transformation ====

setwd("C:/Users/bokhy/Desktop")
accounts <- read.csv("accounts.csv")
names(accounts)[7] <- "account.uuid"

# Calling files and adding "service" column
prod <- read.csv("Production.csv") %>%
  mutate(
    service = case_when(
      activity.game_id < 10000 ~ 'Built-in 350',
      activity.game_id < 10000000 ~ 'BYOG',
      activity.game_id >= 10000000 ~ 'ArcadeNet',
      TRUE ~ 'NA'
    )
  )

# Left-joining files with the same "account_id"
joined_tbl <- left_join(prod, accounts, by = "account.uuid" )

# Cleaning start/end variable
joined_tbl$activity.play_start <-  gsub("@","",joined_tbl$activity.play_start)
joined_tbl$activity.play_start <- gsub("\\..*","",joined_tbl$activity.play_start)
joined_tbl$activity.play_end <-  gsub("@","",joined_tbl$activity.play_end)
joined_tbl$activity.play_end <- gsub("\\..*","",joined_tbl$activity.play_end)


#Change time to "datetime" object
joined_tbl$activity.play_start <- as.POSIXct(strptime(joined_tbl$activity.play_start, "%B %d, %Y %T",tz = "UTC"))
joined_tbl$activity.play_end <- as.POSIXct(strptime(joined_tbl$activity.play_end, "%B %d, %Y %T",tz = "UTC"))


# Separate Date and Time
Y_M_D_start <- paste(year(joined_tbl$activity.play_start), month(joined_tbl$activity.play_start), day(joined_tbl$activity.play_start), sep = "-")
H_M_S_start <- paste(hour(joined_tbl$activity.play_start), minute(joined_tbl$activity.play_start), second(joined_tbl$activity.play_start), sep = ":")
  
Y_M_D_end <- paste(year(joined_tbl$activity.play_end), month(joined_tbl$activity.play_end), day(joined_tbl$activity.play_end), sep = "-")
H_M_S_end <- paste(hour(joined_tbl$activity.play_end), minute(joined_tbl$activity.play_end), second(joined_tbl$activity.play_end), sep = ":")

joined_tbl$play_start_date  <- Y_M_D_start
joined_tbl$play_end_date  <- Y_M_D_end
joined_tbl$play_start_time <- H_M_S_start
joined_tbl$play_end_time <- H_M_S_end  

# Change "play_duration" to numeric value
joined_tbl$activity.play_duration <- as.numeric(gsub(",","",joined_tbl$activity.play_duration))


# Removing unnecessary variables

joined_tbl <- joined_tbl %>% 
  select(machine_uuid,activity.game_title,activity.play_duration,geoip.city_name,remote_ip,tags,account.created_date,account.current_sign_in_ip,account.uuid,activity.1p_buttons,activity.1p_joystick,activity.1p_spinner,activity.2p_buttons,activity.2p_joystick,activity.2p_spinner,geoip.location.lat,geoip.location.lon,geoip.region_name,geoip.country_iso_code,service,Email,Name,play_start_date,play_start_time,play_end_date,play_end_time) %>% 
  filter(between(activity.play_duration, 1, 1000000))
```



### Sidebar {.sidebar}
=============================================================================

#### Customer E-mail

```{r}
selectInput('Email', NULL, unique(joined_tbl$Email))
```


#### Total Play Time

```{r}
gaugeOutput("total_play_time", width = "100%", height = "180px")
```

```{r, context="server"}
output$total_play_time <- renderGauge({
  
  req(input$Email)
        
  selected_customer_email <- joined_tbl$Email[1]
  selected_customer_email <- input$Email
  
  joined_tbl_with_ids <- joined_tbl %>% group_by(machine_uuid) %>% 
    mutate(play_time_total = sum(activity.play_duration))
  
  customer_tbl <- joined_tbl_with_ids %>% 
    filter(Email == selected_customer_email)
        
  gauge(
    unique(customer_tbl$play_time_total), 
    min = 0, 
    max = sum(unique(joined_tbl_with_ids$play_time_total)),
    gaugeSectors(
      success = c(0,(sum(customer_tbl$activity.play_duration)/3)),
      warning = c(33,((sum(customer_tbl$activity.play_duration)/3)*2)),
      danger = c(67,sum(customer_tbl$activity.play_duration))
    ),
    symbol = "seconds"
  )
})
```


Dashboard
=============================================================================

Row
-----------------------------------------------------------------------------

### Machine UUID {.value-box}

```{r}
valueBoxOutput("machine_uuid")
```

```{r, context="server"}
output$machine_uuid <- renderValueBox({
  
  req(input$Email)
        
  selected_customer_email <- joined_tbl$Email[1]
  selected_customer_email <- input$Email
  
  customer_tbl <- joined_tbl %>% 
    filter(Email == selected_customer_email)
  
  valueBox(unique(customer_tbl$machine_uuid), caption = "Machine UUID", color = "primary", icon = "fa-github")
})
```

### Name {.value-box}

```{r}
valueBoxOutput("Name")
```

```{r, context="server"}
output$Name <- renderValueBox({
  
  req(input$Email)
        
  selected_customer_email <- joined_tbl$Email[1]
  selected_customer_email <- input$Email
  
  customer_tbl <- joined_tbl %>% 
    filter(Email == selected_customer_email)
  
  valueBox(unique(customer_tbl$Name), caption ="Name" , color = "info")
})
```

### City Name {.value-box}

```{r}
valueBoxOutput("geoip.city_name")
```

```{r, context="server"}
output$geoip.city_name <- renderValueBox({
  
  req(input$Email)
        
  selected_customer_email <- joined_tbl$Email[1]
  selected_customer_email <- input$Email
  
  customer_tbl <- joined_tbl %>% 
    filter(Email == selected_customer_email)
  
  valueBox(unique(customer_tbl$geoip.city_name), caption = "City Name", color = "warning")
})
```


Row
-----------------------------------------------------------------------------


### Customer Details 

```{css}
table.dataTable thead {
  display:none;
}
table.dataTable tr.selected td, 
table.dataTable td.selected {
  background-color: #c3dbf7 !important;
  border-color: #c3dbf7 !important;
}
```

```{r}
DT::dataTableOutput('customer_info_tbl')
```

```{r, context="server"}
output$customer_info_tbl <- DT::renderDataTable({
        
  req(input$Email)
  
  selected_customer_email <- joined_tbl$Email[1]
  selected_customer_email <- input$Email
  
  customer_info <- joined_tbl %>% 
      filter(Email == selected_customer_email) %>% 
      select(Name,geoip.city_name,geoip.region_name,geoip.country_iso_code,geoip.location.lat,geoip.location.lon,account.uuid,account.current_sign_in_ip) 
  
  DT::datatable(
    customer_info[1,], 
    rownames = NULL,
    options = list(
        dom = 't', 
        bSort = FALSE, 
        paging = FALSE,
        bPaginate = FALSE
    )
  )
})

```

Row
-----------------------------------------------------------------------







Player Map {data-orientation=rows}
============================================================================

Column {data-width=650}
-----------------------------------------------------------------------

### Player Map

```{r}
leaflet() %>% 
  addTiles() %>% 
  fitBounds(-127.44,24.05,-65.30,50.35) %>% 
  addCircleMarkers(joined_tbl$geoip.location.lon, 
                   joined_tbl$geoip.location.lat, 
                   radius = 6, 
                   fill = T,
                   fillOpacity = 0.2,
                   opacity = 0.6,
                   popup = paste(joined_tbl$geoip.city_name,
                                 joined_tbl$geoip.region_name, 
                                 sep = "")) 
```






